run:
  go: '1.24'
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: false
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file

linters:
  enable-all: true
  disable:
    - exhaustruct
    - nonamedreturns
    - wrapcheck
    - gofumpt
    - gci
    - tagliatelle
    - musttag
    - copyloopvar
    - intrange
    - tenv

linters-settings:
  gosec:
    excludes:
      - G401
      - G505
      - G306
      - G115
  stylecheck:
    checks:
      - ST1003
      - ST1005
      - ST1006
      - ST1008
      - ST1011
      - ST1012
      - ST1013
      - ST1015
      - ST1016
      - ST1017
      - ST1018
      - ST1019
      - ST1020
      - ST1021
      - ST1022
      - ST1023

  misspell:
    ignore-words:
      - sub_payed
  whitespace:
    multi-if: true
    multi-func: false
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
          - filippo.io/edwards25519
          - golang.org/x/crypto
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  revive:
    rules:
      - name: dot-imports
        disabled: true
  varnamelen:
    ignore-names:
      - i
      - ok
      - bs
      - err
      - e
      - tx
      - id
      - wg
      - mx
      - db
      - fn
      - in
      - tc
      - t
      - w
      - r
      - c
  funlen:
    lines: 100
    ignore-comments: true
    statements: 50
  cyclop:
    max-complexity: 10
    package-average: 5.0
  gocognit:
    min-complexity: 12

issues:
  exclude-rules:
    - linters:
        - lll
      source: ".*// "
  max-issues-per-linter: 0
  max-same-issues: 0
