package server

import (
	"context"
	"log/slog"
	"net/http"
	"time"

	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/vnchk1/subscription-aggregator/docs" // docs is generated by Swag CLI
	"github.com/vnchk1/subscription-aggregator/internal/config"
	"github.com/vnchk1/subscription-aggregator/internal/handler"
	"github.com/vnchk1/subscription-aggregator/internal/middleware"

	"github.com/labstack/echo/v4"
)

type Server struct {
	echo   *echo.Echo
	cfg    config.ServerConfig
	logger *slog.Logger
}

func New(cfg config.ServerConfig, logger *slog.Logger) *Server {
	e := echo.New()

	e.HideBanner = true
	e.HidePort = true

	return &Server{
		echo:   e,
		cfg:    cfg,
		logger: logger,
	}
}

func (s *Server) Start() error {
	server := &http.Server{
		Addr:         ":" + s.cfg.Port,
		ReadTimeout:  time.Duration(s.cfg.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(s.cfg.WriteTimeout) * time.Second,
	}

	s.logger.Debug("Server starting on port " + s.cfg.Port)

	return s.echo.StartServer(server)
}

func (s *Server) Shutdown(ctx context.Context) error {
	return s.echo.Shutdown(ctx)
}

// GetEchoInstance returns the underlying echo instance for route registration.
func (s *Server) GetEchoInstance() *echo.Echo {
	return s.echo
}

func SetupRouter(e *echo.Echo, subscriptionHandler *handler.SubscriptionHandler, logger *slog.Logger) {
	e.Use(middleware.LoggingMiddleware(logger))

	e.GET("/swagger/*", echoSwagger.WrapHandler)
	// Subscription routes
	subscriptions := e.Group("/subscriptions")
	{
		subscriptions.POST("", subscriptionHandler.CreateSubscription)
		subscriptions.GET("", subscriptionHandler.ListSubscriptions)
		subscriptions.GET("/total-cost", subscriptionHandler.CalculateTotalCost)
		subscriptions.GET("/:id", subscriptionHandler.GetSubscription)
		subscriptions.PUT("/:id", subscriptionHandler.UpdateSubscription)
		subscriptions.DELETE("/:id", subscriptionHandler.DeleteSubscription)
	}

	e.GET("/health", func(c echo.Context) error {
		return c.JSON(200, map[string]string{"status": "ok"})
	})
}
